### ISSUE TITLE
多个CLASS之间的方法调用有点BUG

### ISSUE THREAD

**Issue by 4ra1n** [luelueking/JSource-Obfuscator#2]
今天我用到整个工具，我发现一个目录下多个JAVA文件的CLASS见互相调用的情况中，某些方法名重命名了，但是调用的地方没有改，报错。具体的我之后研究下看看原因

**Comment by luelueking** [comment]
可以 有case的话 我也一起看看

**Comment by 4ra1n** [comment]
![image](https://github.com/luelueking/JSource-Obfuscator/assets/34726933/e73b10a9-1c6a-4455-aede-99bee5c7337c)

这里的 l 应该是 ctClass

**Comment by 4ra1n** [comment]
![image](https://github.com/luelueking/JSource-Obfuscator/assets/34726933/2a4471c9-8b65-48b2-8247-a8d1393b4786)

跨类的方法调用，定义的地方名字改了，但是调用的地方没改

**Comment by 4ra1n** [comment]
![image](https://github.com/luelueking/JSource-Obfuscator/assets/34726933/50dad6dc-687c-4d05-b326-6a48f65c0081)

**Comment by 4ra1n** [comment]
这里的几个问题已经合并
